### ISSUE TITLE
The latest version always fails to deploy in GCP

### ISSUE THREAD

**Issue by ghost** [leitbogioro/SSR.Go#15]
Traceback (most recent call last):
  File "/usr/local/SSR.Go/changepwd.py", line 3, in <module>
    from readjson import ConfPwd
  File "/usr/local/SSR.Go/readjson.py", line 4, in <module>
    from ssrextra import byteify
  File "/usr/local/SSR.Go/ssrextra.py", line 3, in <module>
    import os, random, string, socket, urllib2, base64, qrcode, subprocess
ImportError: No module named qrcode
Traceback (most recent call last):
  File "/usr/local/SSR.Go/connectinfo.py", line 3, in <module>
    import readjson, base64, os, json
  File "/usr/local/SSR.Go/readjson.py", line 4, in <module>
    from ssrextra import byteify
  File "/usr/local/SSR.Go/ssrextra.py", line 3, in <module>
    import os, random, string, socket, urllib2, base64, qrcode, subprocess
ImportError: No module named qrcode

**Comment by leitbogioro** [comment]
Sorry, something about judge whether Aliyun/AlibabaCloud's monitor on your machine went wrong and it may caused SSR.Go can't push to local direction, I have repaired and reinstall it again.
