### ISSUE TITLE
你好，我换过好几个系统，包括你推荐系统，都安装失败

### ISSUE THREAD

**Issue by iwqq** [leitbogioro/SSR.Go#24]
机器是搬瓦工，KVM的。属于小白折腾
网上查询相关内容实在看不懂

重装后立马安装你这个，总是出现下面提示
Traceback (most recent call last):
  File "/usr/local/SSR.Go/connectinfo.py", line 3, in <module>
    import readjson, base64, os, json 
  File "/usr/local/SSR.Go/readjson.py", line 4, in <module>
    from ssrextra import byteify
  File "/usr/local/SSR.Go/ssrextra.py", line 3, in <module>
    import os, random, string, socket, urllib2, base64, qrcode, subprocess, ssl
ImportError: No module named qrcode

**Comment by leitbogioro** [comment]
很明显是qrcode库调用错误，原因是Pip3安装的库文件路径与python运行的库文件路径不一致导致，你系统是不是做了什么修改？建议在干净的debian 9系统上安装，我个人测试过，绝对没问题

**Comment by leitbogioro** [comment]
查过了，安装时逻辑有误，已经修正了，重装下试试
